apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::056539835549:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::056539835549:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CY1N2KBAN0XC
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-22T20:31:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1394"
  uid: b429aa74-94ea-4c25-91e8-c5da36c6ddbc
